<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    
    <!-- 1. Versão do modelo do Maven (para o Maven 3/4, sempre é 4.0.0) -->
    <modelVersion>4.0.0</modelVersion>

    <!-- 2. Herança (Parent): Traz todas as configurações e versões padrão do Spring Boot 3.4.3 -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.3</version>
        <relativePath/>
    </parent>

    <!-- 3. Identificação do nosso projeto (GAV: GroupId, ArtifactId, Version) -->
    <groupId>com.valeshop</groupId>
    <artifactId>financeiro</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>financeiro</name>
    <description>API de Carteira Digital</description>

    <!-- 4. Propriedades: aqui definimos a versão do Java que estamos usando -->
    <properties>
        <java.version>21</java.version>
    </properties>

    <!-- 5. Onde vão entrar as bibliotecas que o projeto usará -->
    <dependencies>
        <!-- Servidor Web REST (Tomcat embutido, Spring MVC, JSON) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Banco de dados e ORM (Hibernate e Spring Data JPA) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <!-- Driver de comunicação com o PostgreSQL -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Lombok: Produtividade (elimina getters, setters e construtores repetitivos) -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Ferramentas de Testes automatizados (JUnit 5, Mockito) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <!-- 6. Plugins de Build (para compilar, empacotar o executável .jar e rodar a aplicação) -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
